### ISSUE TITLE
Add options: Disable Live Bandwidth

### ISSUE THREAD

**Issue by flysatss** [storjdashboard/storjdashboard-internal#1]
Need add option for disable Live Bandwidth.
if many node or vpn connection, live Bandwidth VERY SLOWLY

**Comment by storjdashboard** [comment]
You can do this 

- Settings 
- Features

![image](https://user-images.githubusercontent.com/102604897/222957045-ae266774-f46f-4b8a-b49e-4ce608a04142.png)

You can then unselect / Turn off - on "Display Network Info"

![image](https://user-images.githubusercontent.com/102604897/222957058-9cb08414-a4d5-4d7b-99d5-bb8056aacd2a.png)


I hope that clarifies.

**Comment by flysatss** [comment]
Not an obvious name! Can you name the switch "Live Bandwidth on/off"?
