### ISSUE TITLE
add options: disable user control or variable timeout for relogin

### ISSUE THREAD

**Issue by flysatss** [storjdashboard/storjdashboard-internal#5]
many times enter password.... in local network.... for open node(default) stats
at least it makes no sense to re-enter the password during the day

**Comment by storjdashboard** [comment]
Hi @flysatss 

This is controlled in the PHP.ini or PHP configuration file. 
You can change this immediately within your PHP configuration and it will work for the site.

We will however on this note take forward the idea to have this editable within the website configuration itself. 

This will take place under the 'settings' menu once completed.

**Comment by ItsHass** [comment]
auto-login, by IP range is now enabled as part of 1.0.0.8

**Comment by storjdashboard** [comment]
other timeout functionality / session end functionality should be managed by the php.ini or webserver itself.
